## YAML Template.
---
services:
    sonata.admin.course:
        class: EpitaCourseBundle\Admin\CourseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Course" }
        arguments:
            - ~
            - EpitaCourseBundle\Entity\Course
            - ~
        calls:
            - [ setTranslationDomain, [EpitaCourseBundle]]